// EXEC: cjc %import-path %L %l %f
// EXEC: ./main

import yaml4cj.yaml.*
import std.collection.*

main() {
    // 2023年2月27日 不再提供外部能力

    // var arr: Array<UInt8> = [0x00, 0xBF, 0xBE, 0xBF]
    // var i: Int64 = 0

    // if(!isZ(arr,i)) {
    //    return -1     
    // }

    // var b1: UInt8 = 0xF8
    // var b2: UInt8 = 0xF2 
    // if(width(b1) != 0 || width(b2) != 4) {
    //     return -1
    // }

    // var c: Array<UInt8> = []
    // if(containsChinese(c) != false) {
    //     return -1
    // }

    // var d1: Array<UInt8> = [0x0A,0xBF,0xBE]

    // if(isPrintable(d1, 0) != true) {
    //     return -1
    // }
    return 0
}
