// EXEC: cjc %import-path %L %l %f
// EXEC: ./main

import yaml4cj.yaml.*
import std.collection.*

main() {
    // 2023年2月27日 不再提供外部能力

    // var arr = [NodeTypeT.NodeTypeT_NO_NODE, NodeTypeT.NodeTypeT_SCALAR_NODE, NodeTypeT.NodeTypeT_SEQUENCE_NODE, NodeTypeT.NodeTypeT_MAPPING_NODE]
    // var result: ArrayList<Int64> = ArrayList<Int64>()
    // for(i in 0..arr.size) {
    //     result.append(arr[i].hashCode())
    // }
    // if(result.toArray() != [7735153490726750261, 7735153490726752125, 7735153490726752188, 7735153490726751999]) {
    //     return -1 
    // }    
    return 0
}
