// EXEC: cjc %import-path %L %l %f
// EXEC: ./main

import yaml4cj.yaml.*
import std.env.*
import std.collection.*
import std.fs.*


main() {
    // 2023年2月27日 不再提供外部能力

    // let arr1: Array<UInt8> = [23,21,45,2,54,7,4,78,87,4,98,76]
    // let arr2: ArrayList<UInt8> = ArrayList<UInt8>([23,21,45,2,54,7,4,78,87,4,98,76])
    // let arr3: Array<UInt8> = [40,66,67,68,69,70,71,80,97,100,102]
    // var z: Bool = isZ(arr2, 2)
    // var b: Bool = isBlankz(arr1, 2)
    // var b2: Bool = isBreakz(arr1, 2)
    // if(!isAlpha(arr1, 2)) {
    //     return -1
    // }
    // if(isDigit(arr1, 2)) {
    //     return -1
    // }
    // if(isDigit(arr1, 2)) {
    //     return -1
    // }
    // if(asDigit(arr1, 5) == 22) {
    //     return 0
    // }
    // var hex1: Bool = isHex(arr1, 2)
    // if(hex1) {
    //     return -1
    // }
    // if(asHex(arr3, 2) != 12) {
    //     return -1
    // }
    // if(!isAscii(arr2, 2)) {
    //     return -1
    // }
    // if(isCRLF(arr1, 2)) {
    //     return -1
    // }

    // if(!isPrintable(arr2, 2)) {
    //     return -1
    // }

    // if(b) {
    //     return -1
    // }
    // if(b2) {
    //     return -1
    // }

    // if(asHex(arr3, 9) != 13) {
    //     return -1
    // }

    // if(asHex(arr3, 0) == 13) {
    //     return -1
    // }

    // if(z) {
    //     return -1
    // }
    return 0
}
