package yaml4cj
import std.collection.*

@Test
class Mytest2{
    @TestCase
    func mytest1(): Unit {
        // 2023年2月27日 不再提供外部能力
        
        // let arr1: Array<UInt8> = [65,66,67,68,69,70,71,80,97,100,102]
        // let arr2: ArrayList<UInt8> = ArrayList<UInt8>([65,66,67,68,69,70,71,80,97,100,102])

        // @Assert(asDigit(arr1, 5), 22)
        // @Assert(asDigit(arr2, 8), 49)

        // @Assert(asHex(arr1, 2), 12)
        // @Assert(asHex(arr2, 6), 23)

    }
}
