/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

package commonmark4cj.commonmark

public type NodeType = String

let DocumentType: NodeType = "Document"
let HeadingType: NodeType = "Heading"
let ParagraphType: NodeType = "Paragraph"
let BlockQuoteType: NodeType = "BlockQuote"
let BulletListType: NodeType = "BulletList"
let FencedCodeBlockType: NodeType = "FencedCodeBlock"
let HtmlBlockType: NodeType = "HtmlBlock"
let ThematicBreakType: NodeType = "ThematicBreak"
let IndentedCodeBlockType: NodeType = "IndentedCodeBlock"
let LinkType: NodeType = "Link"
let ListBlockType: NodeType = "ListBlock"
let ListItemType: NodeType = "ListItem"
let OrderedListType: NodeType = "OrderedList"
let ImageType: NodeType = "Image"
let EmphasisType: NodeType = "Emphasis"
let StrongEmphasisType: NodeType = "StrongEmphasis"
let TextType: NodeType = "Text"
let CodeType: NodeType = "Code"
let HtmlInlineType: NodeType = "HtmlInline"
let SoftLineBreakType: NodeType = "SoftLineBreak"
let HardLineBreakType: NodeType = "HardLineBreak"
let LinkReferenceDefinitionType: NodeType = "LinkReferenceDefinition"
